module.exports = [
    {
        "IPPhone": null,
        "additionalComments": "Correct Dept: Procurement Office - Purchasing Operations",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Tarrytown",
        "companyCode": "Frontier Consulting Service",
        "createDate": "2020-06-12 16:15:26",
        "createdBy": "dpalermo",
        "dateOfBirth": "1990-07-21 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2021-06-18 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Karen",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00010495",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Forrester",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "dpalermo@montefiore.org",
        "managerPhone": "914-555-5555",
        "managerSourceUniqueId": "019165",
        "middleNameOrInitial": null,
        "mmcEmailRequest": "Y",
        "nameSuffix": null,
        "noSSN": "Y",
        "nonMonteEmail": "kforrester@forrester.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C631665",
        "ssn": null,
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2020-06-15 04:00:00",
        "startDateStr": null,
        "statusCode": null,
        "title": "Data Management Analyst",
        "udcid": null,
        "updateDate": "2020-06-12 16:15:26",
        "updatedBy": "dpalermo",
        "worklistStatus": "Initial"
    },
    {
        "IPPhone": null,
        "additionalComments": "Department: Please extend user access again. Procurement Office - Purchasing Department. ",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Tarrytown",
        "companyCode": "Frontier Consulting Service",
        "createDate": "2020-06-12 16:28:35",
        "createdBy": "dpalermo",
        "dateOfBirth": "1978-08-01 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2021-01-08 05:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "End Date is in the past: 01/08/2021",
        "firstName": "Tom",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00010496",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Thompson",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "dpalermo@montefiore.org",
        "managerPhone": "914-555-5555",
        "managerSourceUniqueId": "015161",
        "middleNameOrInitial": null,
        "mmcEmailRequest": "Y",
        "nameSuffix": null,
        "noSSN": "Y",
        "nonMonteEmail": "ttompson@gmail.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": "Form is invalid.  Must be signed within the last 30 days.",
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C631666",
        "ssn": null,
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2020-01-07 05:00:00",
        "startDateStr": null,
        "statusCode": null,
        "title": "Data Management Analyst",
        "udcid": null,
        "updateDate": "2021-04-22 14:42:13",
        "updatedBy": "mmishra",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "Correct Dept: Procurement Office. Correct Title: Administrative Assistant",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Tarrytown",
        "companyCode": "Frontier Consulting Service",
        "createDate": "2020-06-12 16:35:13",
        "createdBy": "dpalermo",
        "dateOfBirth": "1976-11-20 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2021-06-25 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Jasmine",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00010497",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Jones",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "dpalermo@montefiore.org",
        "managerPhone": "914-555-5555",
        "managerSourceUniqueId": "019165",
        "middleNameOrInitial": null,
        "mmcEmailRequest": "Y",
        "nameSuffix": null,
        "noSSN": "Y",
        "nonMonteEmail": "jjones@gmail.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C631667",
        "ssn": null,
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2020-06-22 04:00:00",
        "startDateStr": null,
        "statusCode": null,
        "title": "Other",
        "udcid": null,
        "updateDate": "2020-06-12 16:35:13",
        "updatedBy": "dpalermo",
        "worklistStatus": "Initial"
    },
    {
        "IPPhone": null,
        "additionalComments": "no training required. thanks",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "White Plains",
        "companyCode": "CIOX",
        "createDate": "2020-06-12 19:54:58",
        "createdBy": "dpalermo",
        "dateOfBirth": "1981-05-21 05:00:00",
        "dateOfBirthStr": null,
        "department": "Patient Services",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Vendor",
        "endDate": "2021-06-12 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Eileen",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00010501",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Rothchild",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "dpalermo@montefiore.org",
        "managerPhone": "914-555-5555",
        "managerSourceUniqueId": "092906",
        "middleNameOrInitial": null,
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "Y",
        "nonMonteEmail": "eileenr@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C631671",
        "ssn": null,
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2020-06-12 04:00:00",
        "startDateStr": null,
        "statusCode": null,
        "title": "Other",
        "udcid": null,
        "updateDate": "2020-06-12 19:54:58",
        "updatedBy": "dpalermo",
        "worklistStatus": "Initial"
    },
    {
        "IPPhone": null,
        "additionalComments": "this is a demo",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Burke Rehab",
        "companyCode": "fghj",
        "createDate": "2021-04-09 16:25:21",
        "createdBy": "mmishra",
        "dateOfBirth": "1997-09-01 05:00:00",
        "dateOfBirthStr": null,
        "department": "Audiology",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Clinical Vendor",
        "endDate": "2021-04-30 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "Y",
        "epfRequest": "Y",
        "epicRequest": "Y",
        "errorMessage": null,
        "firstName": "Mittul",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00010548",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Mishra",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "David@montefiore.org",
        "managerPhone": "914-437-9237 Ext 456",
        "managerSourceUniqueId": "012356",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "Y",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "mmishra@hjjj.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": null,
        "sourceUniqueId": "C631734",
        "ssn": "3456",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-04-09 04:00:00",
        "startDateStr": null,
        "statusCode": null,
        "title": "4th Yr Med Student",
        "udcid": null,
        "updateDate": "2021-04-09 16:26:37",
        "updatedBy": "mmishra",
        "worklistStatus": "Initial"
    },
    {
        "IPPhone": null,
        "additionalComments": "test",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Weiler",
        "companyCode": "dummy company",
        "createDate": "2021-04-16 15:00:04",
        "createdBy": "mmishra",
        "dateOfBirth": "1986-02-15 05:00:00",
        "dateOfBirthStr": null,
        "department": "Surgery",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Vendor",
        "endDate": "2021-12-15 05:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "Y",
        "epfRequest": "N",
        "epicRequest": "Y",
        "errorMessage": null,
        "firstName": "rich",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00010578",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "micheal",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "lseryifuds@montefiore.org",
        "managerPhone": "913-234-7890",
        "managerSourceUniqueId": "41746218",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "Y",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "michric@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": null,
        "sourceUniqueId": "C631743",
        "ssn": "123-23-3456",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2020-09-01 04:00:00",
        "startDateStr": null,
        "statusCode": null,
        "title": "Transporter",
        "udcid": null,
        "updateDate": "2021-04-16 15:00:04",
        "updatedBy": "mmishra",
        "worklistStatus": "Initial"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:32:36",
        "createdBy": "Job16527",
        "dateOfBirth": "1982-12-12 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-03-25 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "Y",
        "errorMessage": null,
        "firstName": "Donald",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011480",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Drake",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "123456",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "dd@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633634",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-03-25 04:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-03-25 16:23:19",
        "updatedBy": "beweeks",
        "worklistStatus": "Ready"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:32:36",
        "createdBy": "Job16527",
        "dateOfBirth": "1971-01-01 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-03-25 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Evin",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011481",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Edmondson",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "12456",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "ee@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633635",
        "ssn": "4498",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-03-25 04:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-03-25 16:30:21",
        "updatedBy": "beweeks",
        "worklistStatus": "Ready"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:32:36",
        "createdBy": "Job16527",
        "dateOfBirth": "1982-12-12 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-03-25 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Veronica",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011580",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Van Wycke",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "123456",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "vv@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633634",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-03-25 04:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-03-25 16:31:30",
        "updatedBy": "beweeks",
        "worklistStatus": "Ready"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:33:38",
        "createdBy": "Job16529",
        "dateOfBirth": "1972-02-02 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": null,
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "[Invalid StartDate '', Invalid EndDate ''], Missing required field(s): [StartDate, EndDate, ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Yvette",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011584",
            "worklistSeqNum": 1
        },
        "jobControlNumber": 16529,
        "lastName": "Young",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "yy@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633638",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": null,
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:33:39",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "More sample data",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Corp",
        "createDate": "2021-01-28 15:13:43",
        "createdBy": "Job16523",
        "dateOfBirth": "1985-03-24 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2021-06-30 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Felicia",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011673",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Frawley",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "123456",
        "middleNameOrInitial": "F",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "FFalstaff@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": "Screen Shot",
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633627",
        "ssn": "4321",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-02-15 05:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-02-16 19:29:03",
        "updatedBy": "beweeks",
        "worklistStatus": "Rejected"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:24:02",
        "createdBy": "Job16525",
        "dateOfBirth": "1975-05-01 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-02-08 05:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Samuel",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011677",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Stevenson",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "123456",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "SStevenson@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633631",
        "ssn": "4498",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-02-08 05:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-02-16 14:48:24",
        "updatedBy": "beweeks",
        "worklistStatus": "Initial"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:32:36",
        "createdBy": "Job16527",
        "dateOfBirth": "1982-12-12 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-03-25 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Zelda",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011680",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Zimmerman",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "123456",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "zz@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633634",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-03-25 04:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-03-25 16:33:21",
        "updatedBy": "beweeks",
        "worklistStatus": "Ready"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:32:36",
        "createdBy": "Job16527",
        "dateOfBirth": "1971-01-01 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-03-25 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": null,
        "firstName": "Adam",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011681",
            "worklistSeqNum": 1
        },
        "jobControlNumber": null,
        "lastName": "Atkins",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgrname@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "124567",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "aa@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633635",
        "ssn": "4498",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-03-25 04:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-03-25 16:34:13",
        "updatedBy": "beweeks",
        "worklistStatus": "Ready"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:33:38",
        "createdBy": "Job16529",
        "dateOfBirth": "1972-02-02 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": null,
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "[Invalid StartDate '', Invalid EndDate ''], Missing required field(s): [StartDate, EndDate, ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Brenda",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011684",
            "worklistSeqNum": 1
        },
        "jobControlNumber": 16529,
        "lastName": "Benson",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "bb@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633638",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": null,
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:33:39",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:33:38",
        "createdBy": "Job16529",
        "dateOfBirth": "1973-03-03 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": null,
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "[Invalid StartDate '', Invalid EndDate ''], Missing required field(s): [StartDate, EndDate, ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Chris",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011685",
            "worklistSeqNum": 1
        },
        "jobControlNumber": 16529,
        "lastName": "Chisolm",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "cc@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633639",
        "ssn": "4498",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": null,
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:33:39",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:34:05",
        "createdBy": "Job16530",
        "dateOfBirth": "1974-04-04 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": null,
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "[Invalid StartDate '', Invalid EndDate ''], Missing required field(s): [StartDate, EndDate, ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Danielle",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011686",
            "worklistSeqNum": 1
        },
        "jobControlNumber": 16530,
        "lastName": "Davis",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "dd@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633640",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": null,
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:34:05",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "TEST",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:34:30",
        "createdBy": "Job16531",
        "dateOfBirth": "1975-05-05 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": null,
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "[Invalid StartDate '', Invalid EndDate ''], Missing required field(s): [StartDate, EndDate, ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Edmond",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011689",
            "worklistSeqNum": 1
        },
        "jobControlNumber": 16531,
        "lastName": "Ellison",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "ee@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633643",
        "ssn": "4498",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": null,
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:34:31",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "TEST",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:35:27",
        "createdBy": "Job16532",
        "dateOfBirth": "1976-06-06 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": null,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": "2022-02-08 05:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "Missing required field(s): [ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Francis",
        "firstNameCleaned": null,
        "gender": "M",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011689",
            "worklistSeqNum": 2
        },
        "jobControlNumber": 16532,
        "lastName": "Farley",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "ff@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633645",
        "ssn": "4498",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2021-02-08 05:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:35:28",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "Jane Comment",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Tarrytown",
        "companyCode": "ABC Company",
        "createDate": "2021-02-16 16:39:35",
        "createdBy": "Job16537",
        "dateOfBirth": "1982-02-02 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Clinical Consultant",
        "endDate": "2021-08-31 04:00:00",
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "Invalid Location 'Mount Vernon'",
        "firstName": "Sarah",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011689",
            "worklistSeqNum": 3
        },
        "jobControlNumber": null,
        "lastName": "Smith",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "mgr@montefiore.org",
        "managerPhone": "914-123-4567",
        "managerSourceUniqueId": "500725",
        "middleNameOrInitial": "S",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "abc@gmail.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633651",
        "ssn": "4321",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": "2020-08-01 04:00:00",
        "startDateStr": null,
        "statusCode": "A",
        "title": "Data Management Analyst",
        "udcid": null,
        "updateDate": "2021-02-16 17:13:16",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    },
    {
        "IPPhone": null,
        "additionalComments": "",
        "affiliateEmailRequest": "N",
        "assignedMonteId": null,
        "campusCode": "Other",
        "companyCode": "ABC Company",
        "createDate": "2021-01-28 15:33:38",
        "createdBy": "Job16529",
        "dateOfBirth": "1972-02-02 05:00:00",
        "dateOfBirthStr": null,
        "department": "Montefiore IT",
        "division": null,
        "documentCount": 0,
        "employeeGroup": null,
        "employeeSubGroup": "Non-clinical Consultant",
        "endDate": null,
        "endDateStr": null,
        "epcsHardTokenRequest": "N",
        "epfRequest": "N",
        "epicRequest": "N",
        "errorMessage": "[Invalid StartDate '', Invalid EndDate ''], Missing required field(s): [StartDate, EndDate, ManagerPhone, ManagerEmail, MHS-ManagerID], Invalid MHS Manager ID - must be number between 4 & 10 digits long",
        "firstName": "Theresa",
        "firstNameCleaned": null,
        "gender": "F",
        "homeDriveRequest": "N",
        "id": {
            "worklistId": "wk.00011884",
            "worklistSeqNum": 1
        },
        "jobControlNumber": 16529,
        "lastName": "Tucker",
        "lastNameCleaned": null,
        "loaReturnDate": null,
        "loaStartDate": null,
        "managerEmail": "",
        "managerPhone": "",
        "managerSourceUniqueId": "",
        "middleNameOrInitial": "D",
        "mmcEmailRequest": "N",
        "nameSuffix": null,
        "noSSN": "N",
        "nonMonteEmail": "tt@aol.com",
        "officeAddress": null,
        "officeCity": null,
        "officePhone": null,
        "officeState": null,
        "officeZipCode": null,
        "preHireFlag": null,
        "preferredName": null,
        "reviewerComments": null,
        "sourceSystem": "NonEmployee",
        "sourceUniqueId": "C633638",
        "ssn": "8023",
        "ssn4": null,
        "ssn4Hash": null,
        "ssnHash": null,
        "startDate": null,
        "startDateStr": null,
        "statusCode": "A",
        "title": "Consultant Coder",
        "udcid": null,
        "updateDate": "2021-01-28 15:33:39",
        "updatedBy": "beweeks",
        "worklistStatus": "OnHold"
    }
]