module.exports = {
    "acceptDate": null,
    "additionalComments": null,
    "createDate": "2021-04-23 18:51:56",
    "createdBy": "mmishra",
    "fileList": [
        {
            "baseName": "wk.00000717_20181105_ConfAgree_Contreras.pdf",
            "directory": false,
            "fileContents": null,
            "fileModificationDate": "2018-11-05 05:04 PM",
            "fileName": "C:\\IDHub\\FileStore\\wk.00010489\\wk.00000717_20181105_ConfAgree_Contreras.pdf",
            "filePermissions": null,
            "fileSize": 0,
            "fileURL": "http://localhost:8080/docs/FileStore/wk.00010489/wk.00000717_20181105_ConfAgree_Contreras.pdf",
            "parentDir": "C:\\IDHub\\FileStore\\wk.00010489\\wk.00000717_20181105_ConfAgree_Contreras.pdf",
            "parentURL": "http://localhost:8080/docs/FileStore/wk.00010489/"
        }
    ],
    "processedDate": null,
    "requesterUser": {
        "createDate": "2018-03-26 04:00:00",
        "createdBy": "system",
        "roleMap": [
            {
                "accessActiveFlag": 1,
                "createdBy": "system",
                "id": {
                    "roleId": "Requestor",
                    "userId": "mmishra"
                },
                "updatedBy": "system"
            }
        ],
        "updateDate": "2018-03-26 04:00:00",
        "updatedBy": "system",
        "userActiveFlag": 1,
        "userEmail": "mmishra@montefiore.org",
        "userFirstName": "Mittul",
        "userId": "mmishra",
        "userLastName": "Mishra",
        "userPhone": "914-457-6018"
    },
    "requesterUserId": "mmishra",
    "reviewerComments": null,
    "reviewerUserId": null,
    "submitDate": null,
    "updateDate": "2021-04-23 18:51:56",
    "updateRequestor": true,
    "updatedBy": "mmishra",
    "workLists": [
        {
            "IPPhone": null,
            "additionalComments": "Needs Email. Prior AD Account dciraco",
            "affiliateEmailRequest": "N",
            "assignedMonteId": null,
            "campusCode": "Mt. Vernon",
            "companyCode": "Montefiore School of Nursing",
            "createDate": "2020-06-11 20:50:39",
            "createdBy": "Job14161",
            "dateOfBirth": "1981-04-15 05:00:00",
            "dateOfBirthStr": null,
            "department": "Nursing",
            "division": null,
            "documentCount": 0,
            "employeeGroup": null,
            "employeeSubGroup": "Student",
            "endDate": "2021-12-21 05:00:00",
            "endDateStr": null,
            "epcsHardTokenRequest": "N",
            "epfRequest": "N",
            "epicRequest": "N",
            "errorMessage": null,
            "firstName": "Angela",
            "firstNameCleaned": null,
            "gender": "F",
            "homeDriveRequest": "N",
            "id": {
                "worklistId": "wk.00010489",
                "worklistSeqNum": 1
            },
            "jobControlNumber": null,
            "lastName": "Corning",
            "lastNameCleaned": null,
            "loaReturnDate": null,
            "loaStartDate": null,
            "managerEmail": "dpalermo@montefiore.org",
            "managerPhone": "914-555-5555",
            "managerSourceUniqueId": "202197",
            "middleNameOrInitial": null,
            "mmcEmailRequest": "Y",
            "nameSuffix": null,
            "noSSN": "Y",
            "nonMonteEmail": "acorning@gmail.com",
            "officeAddress": null,
            "officeCity": null,
            "officePhone": null,
            "officeState": null,
            "officeZipCode": null,
            "preHireFlag": null,
            "preferredName": null,
            "reviewerComments": null,
            "sourceSystem": "NonEmployee",
            "sourceUniqueId": "C631654",
            "ssn": null,
            "ssn4": null,
            "ssn4Hash": null,
            "ssnHash": null,
            "startDate": "2020-06-15 04:00:00",
            "startDateStr": null,
            "statusCode": "A",
            "title": "Nursing Student",
            "udcid": null,
            "updateDate": "2021-04-23 18:51:56",
            "updatedBy": "mmishra",
            "worklistStatus": "Processed"
        },
        {
            "IPPhone": null,
            "additionalComments": "Needs Email. Prior AD Account vcoronel",
            "affiliateEmailRequest": "N",
            "assignedMonteId": null,
            "campusCode": "Mt. Vernon",
            "companyCode": "Montefiore School of Nursing",
            "createDate": "2020-06-11 20:50:39",
            "createdBy": "Job14161",
            "dateOfBirth": "1991-08-31 04:00:00",
            "dateOfBirthStr": null,
            "department": "Nursing",
            "division": null,
            "documentCount": 0,
            "employeeGroup": null,
            "employeeSubGroup": "Student",
            "endDate": "2021-12-21 05:00:00",
            "endDateStr": null,
            "epcsHardTokenRequest": "N",
            "epfRequest": "N",
            "epicRequest": "N",
            "errorMessage": null,
            "firstName": "Julie",
            "firstNameCleaned": null,
            "gender": "F",
            "homeDriveRequest": "N",
            "id": {
                "worklistId": "wk.00010489",
                "worklistSeqNum": 2
            },
            "jobControlNumber": null,
            "lastName": "McCoy",
            "lastNameCleaned": null,
            "loaReturnDate": null,
            "loaStartDate": null,
            "managerEmail": "dpalermo@montefiore.org",
            "managerPhone": "914-555-5555",
            "managerSourceUniqueId": "202197",
            "middleNameOrInitial": null,
            "mmcEmailRequest": "Y",
            "nameSuffix": null,
            "noSSN": "Y",
            "nonMonteEmail": "julie@lboat.com",
            "officeAddress": null,
            "officeCity": null,
            "officePhone": null,
            "officeState": null,
            "officeZipCode": null,
            "preHireFlag": null,
            "preferredName": null,
            "reviewerComments": null,
            "sourceSystem": "NonEmployee",
            "sourceUniqueId": "C631655",
            "ssn": null,
            "ssn4": null,
            "ssn4Hash": null,
            "ssnHash": null,
            "startDate": "2020-06-15 04:00:00",
            "startDateStr": null,
            "statusCode": "A",
            "title": "Nursing Student",
            "udcid": null,
            "updateDate": "2021-04-19 18:43:28",
            "updatedBy": "mmishra",
            "worklistStatus": "Processed"
        },
        {
            "IPPhone": null,
            "additionalComments": "Needs Email. Prior AD Account xxx",
            "affiliateEmailRequest": "N",
            "assignedMonteId": null,
            "campusCode": "Mt. Vernon",
            "companyCode": "Montefiore School of Nursing",
            "createDate": "2020-06-11 20:50:39",
            "createdBy": "Job14161",
            "dateOfBirth": "1979-11-21 05:00:00",
            "dateOfBirthStr": null,
            "department": "Nursing",
            "division": null,
            "documentCount": 0,
            "employeeGroup": null,
            "employeeSubGroup": "Student",
            "endDate": "2021-12-21 05:00:00",
            "endDateStr": null,
            "epcsHardTokenRequest": "N",
            "epfRequest": "N",
            "epicRequest": "N",
            "errorMessage": null,
            "firstName": "Betty",
            "firstNameCleaned": null,
            "gender": "F",
            "homeDriveRequest": "N",
            "id": {
                "worklistId": "wk.00010489",
                "worklistSeqNum": 3
            },
            "jobControlNumber": null,
            "lastName": "White",
            "lastNameCleaned": null,
            "loaReturnDate": null,
            "loaStartDate": null,
            "managerEmail": "dpalermo@montefiore.org",
            "managerPhone": "914-555-5555",
            "managerSourceUniqueId": "202197",
            "middleNameOrInitial": null,
            "mmcEmailRequest": "Y",
            "nameSuffix": null,
            "noSSN": "Y",
            "nonMonteEmail": "bwhite@yahoo.com",
            "officeAddress": null,
            "officeCity": null,
            "officePhone": null,
            "officeState": null,
            "officeZipCode": null,
            "preHireFlag": null,
            "preferredName": null,
            "reviewerComments": null,
            "sourceSystem": "NonEmployee",
            "sourceUniqueId": "C631656",
            "ssn": null,
            "ssn4": null,
            "ssn4Hash": null,
            "ssnHash": null,
            "startDate": "2020-06-15 04:00:00",
            "startDateStr": null,
            "statusCode": "A",
            "title": "Nursing Student",
            "udcid": null,
            "updateDate": "2020-06-11 20:50:40",
            "updatedBy": "dpalermo",
            "worklistStatus": "Processed"
        },
        {
            "IPPhone": null,
            "additionalComments": "Re-activate Monte Email Acct",
            "affiliateEmailRequest": "N",
            "assignedMonteId": null,
            "campusCode": "Mt. Vernon",
            "companyCode": "Montefiore School of Nursing",
            "createDate": "2020-06-11 20:50:39",
            "createdBy": "Job14161",
            "dateOfBirth": "1980-02-16 05:00:00",
            "dateOfBirthStr": null,
            "department": "Nursing",
            "division": null,
            "documentCount": 0,
            "employeeGroup": null,
            "employeeSubGroup": "Student",
            "endDate": "2021-12-21 05:00:00",
            "endDateStr": null,
            "epcsHardTokenRequest": "N",
            "epfRequest": "N",
            "epicRequest": "N",
            "errorMessage": null,
            "firstName": "Larry",
            "firstNameCleaned": null,
            "gender": "M",
            "homeDriveRequest": "N",
            "id": {
                "worklistId": "wk.00010489",
                "worklistSeqNum": 4
            },
            "jobControlNumber": null,
            "lastName": "Watson",
            "lastNameCleaned": null,
            "loaReturnDate": null,
            "loaStartDate": null,
            "managerEmail": "dpalermo@montefiore.org",
            "managerPhone": "914-555-5555",
            "managerSourceUniqueId": "202197",
            "middleNameOrInitial": null,
            "mmcEmailRequest": "Y",
            "nameSuffix": null,
            "noSSN": "Y",
            "nonMonteEmail": "larry@yahoo.com",
            "officeAddress": null,
            "officeCity": null,
            "officePhone": null,
            "officeState": null,
            "officeZipCode": null,
            "preHireFlag": null,
            "preferredName": null,
            "reviewerComments": null,
            "sourceSystem": "NonEmployee",
            "sourceUniqueId": "C631657",
            "ssn": null,
            "ssn4": null,
            "ssn4Hash": null,
            "ssnHash": null,
            "startDate": "2020-06-15 04:00:00",
            "startDateStr": null,
            "statusCode": "A",
            "title": "Nursing Student",
            "udcid": null,
            "updateDate": "2020-06-11 20:50:40",
            "updatedBy": "dpalermo",
            "worklistStatus": "Processed"
        },
        {
            "IPPhone": null,
            "additionalComments": "Needs Email. Prior AD Account xxx",
            "affiliateEmailRequest": "N",
            "assignedMonteId": null,
            "campusCode": "Mt. Vernon",
            "companyCode": "Montefiore School of Nursing",
            "createDate": "2020-06-11 20:50:39",
            "createdBy": "Job14161",
            "dateOfBirth": "1973-06-04 04:00:00",
            "dateOfBirthStr": null,
            "department": "Nursing",
            "division": null,
            "documentCount": 0,
            "employeeGroup": null,
            "employeeSubGroup": "Student",
            "endDate": "2021-06-02 04:00:00",
            "endDateStr": null,
            "epcsHardTokenRequest": "N",
            "epfRequest": "N",
            "epicRequest": "N",
            "errorMessage": null,
            "firstName": "Katie",
            "firstNameCleaned": null,
            "gender": "F",
            "homeDriveRequest": "N",
            "id": {
                "worklistId": "wk.00010489",
                "worklistSeqNum": 5
            },
            "jobControlNumber": null,
            "lastName": "Segal",
            "lastNameCleaned": null,
            "loaReturnDate": null,
            "loaStartDate": null,
            "managerEmail": "dpalermo@montefiore.org",
            "managerPhone": "914-555-5555",
            "managerSourceUniqueId": "202197",
            "middleNameOrInitial": null,
            "mmcEmailRequest": "Y",
            "nameSuffix": null,
            "noSSN": "Y",
            "nonMonteEmail": "katiesegal@gmail.com",
            "officeAddress": null,
            "officeCity": null,
            "officePhone": null,
            "officeState": null,
            "officeZipCode": null,
            "preHireFlag": null,
            "preferredName": null,
            "reviewerComments": null,
            "sourceSystem": "NonEmployee",
            "sourceUniqueId": "C631658",
            "ssn": null,
            "ssn4": null,
            "ssn4Hash": null,
            "ssnHash": null,
            "startDate": "2020-06-15 04:00:00",
            "startDateStr": null,
            "statusCode": "A",
            "title": "Nursing Student",
            "udcid": null,
            "updateDate": "2020-06-11 20:50:40",
            "updatedBy": "dpalermo",
            "worklistStatus": "Processed"
        },
        {
            "IPPhone": null,
            "additionalComments": "Re-activate Monte Email Acct",
            "affiliateEmailRequest": "N",
            "assignedMonteId": null,
            "campusCode": "Mt. Vernon",
            "companyCode": "Montefiore School of Nursing",
            "createDate": "2020-06-11 20:50:39",
            "createdBy": "Job14161",
            "dateOfBirth": "1987-04-11 04:00:00",
            "dateOfBirthStr": null,
            "department": "Nursing",
            "division": null,
            "documentCount": 0,
            "employeeGroup": null,
            "employeeSubGroup": "Student",
            "endDate": "2020-12-21 05:00:00",
            "endDateStr": null,
            "epcsHardTokenRequest": "N",
            "epfRequest": "N",
            "epicRequest": "N",
            "errorMessage": null,
            "firstName": "Kelly",
            "firstNameCleaned": null,
            "gender": "F",
            "homeDriveRequest": "N",
            "id": {
                "worklistId": "wk.00010489",
                "worklistSeqNum": 6
            },
            "jobControlNumber": null,
            "lastName": "Clarkson",
            "lastNameCleaned": null,
            "loaReturnDate": null,
            "loaStartDate": null,
            "managerEmail": "dpalermo@montefiore.org",
            "managerPhone": "914-555-5555",
            "managerSourceUniqueId": "202197",
            "middleNameOrInitial": null,
            "mmcEmailRequest": "Y",
            "nameSuffix": null,
            "noSSN": "Y",
            "nonMonteEmail": "kellyclarkson@agt.com",
            "officeAddress": null,
            "officeCity": null,
            "officePhone": null,
            "officeState": null,
            "officeZipCode": null,
            "preHireFlag": null,
            "preferredName": null,
            "reviewerComments": null,
            "sourceSystem": "NonEmployee",
            "sourceUniqueId": "C631659",
            "ssn": null,
            "ssn4": null,
            "ssn4Hash": null,
            "ssnHash": null,
            "startDate": "2020-06-15 04:00:00",
            "startDateStr": null,
            "statusCode": "A",
            "title": "Nursing Student",
            "udcid": null,
            "updateDate": "2020-06-11 20:50:40",
            "updatedBy": "dpalermo",
            "worklistStatus": "Processed"
        }
    ],
    "worklistId": "wk.00010489",
    "worklistStatus": null
}
